version: '3'
services:

  pgadmin:
   
    image: dpage/pgadmin4

    ports:
      - '9000:80'
    network_mode: bridge

    # Link this container to the postgres container with hostname 'postgres'
    external_links:
      - postgres:postgres

    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
