version: '3'
services:

  postgres:

    image: postgres:alpine

    ports:
      - '5432:5432'
    network_mode: bridge
    container_name: postgres

    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '12341234'
      POSTGRES_DB: 'postgres'

    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

